on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    build_packs:
       runs-on: ubuntu-22.04
       name: Merged Update Request
       steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build All Package
          uses: ./
          id: arch-build
        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
           name: artifact_package
           path: "*.pkg.tar.zst"

