on:
    workflow_dispatch:
    pull_request:
        branches:
            - 'package/**'
        types:
            - closed

jobs:
    build_packs:
       runs-on: ubuntu-22.04
       name: Merged Update Request
       steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build All Package
          uses: ./.github/workflows/build_container/
          id: arch-build
        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
           name: artifact_package
           path: "*.pkg.tar.zst"

    update_repo:
          runs-on: ubuntu-22.04
          needs: build_packs
          name: Update Repos
          steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Download Artifact
              uses: actions/download-artifact@v3
              with:
                name: artifact_package
            - name: Update Repo Data
              uses: ./.github/workflows/upload_container/
              id: arch-upload
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifact_db
                path: "*.pkg.tar.zst"
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifact_db
                path: "*.pkg.tar.zst.sig"
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifact_db
                path: "ardent-staging.*.tar.xz"
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifact_db
                path: "ardent-stable.*.tar.xz"
    upload_stgrepo:
        runs-on: ubuntu-22.04
        needs: update_repo
        permissions:
            pull-requests: write
            contents: write
            repository-projects: write
        steps:
            - name: Checkout Staging Repo
              uses: actions/checkout@v3
              with:
                repository: atolycs/ardent-repo
            - name: Download Artifacts
              uses: actions/download-artifact@v3
              with:
                name: artifact_db
                path: ./x86_64
            - name: Git config
              env:
                GIT_ACTION_MAIL: ${{ secrets.GIT_ACTION_EMAIL }}
              run: |
                git config --local user.name "Atolycs by Github Actions"
                git config --local user.email ${GIT_ACTION_MAIL}
            - name: Push
              run: |
                git add -A
                git commit -m "[Action] Update Repository"
                git pull
                git push 
