on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
            - master
        types:
            - closed

jobs:
    build_packs:
       runs-on: ubuntu-22.04
       name: Merged Update Request
       steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build All Package
          uses: ./.github/workflows/build_container/
          id: arch-build
        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
           name: artifact_package
           path: "*.pkg.tar.zst"
    update_repo:
          runs-on: ubuntu-22.04
          needs: build_packs
          name: Update Repos
          steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                repository: atolycs/ardent-repo
                path: ./ardent-repos

            - name: Download Artifact
              uses: actions/download-artifact@v3
              with:
                name: artifact_package
                path: ./ardent-repos

            - name: Update Repo Data
              uses: ./.github/workflows/upload_container/
                id: arch-upload

