on:
    workflow_dispatch:
    pull_request:
        branches:
            - 'package/**'
        types:
            - closed

jobs:
    build_packs:
       runs-on: ubuntu-22.04
       name: Merged Update Request
       steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build All Package
          uses: ./.github/workflows/build_container/
          id: arch-build
        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
           name: artifact_package
           path: "*.pkg.tar.zst"

    update_repo:
          runs-on: ubuntu-22.04
          needs: build_packs
          name: Update Repos
          steps:
            - name: checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Download Artifact
              uses: actions/download-artifact@v3
              with:
                name: artifact_package
                path: ./x86_64

            - name: Update Repo Data
              uses: ./.github/workflows/upload_container/
              id: arch-upload
              env:
                GPG_REPO_SEC: ${{ secrets.REPO_DEPLOY_KEY }}
                TEMP_GPGKEY: ${{ secrets.GPG_KEY }}
                TEMP_OWNER_TRUST: ${{ secrets.OWNER_TRUST }}
                TEMP_GPG_KEYFINGER_SEC: ${{ secrets.GPG_KEYFINGER_SEC }}
                build_arch: "x86_64"
            - name: Deploy Staging Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: ./x86_64
                  destination_dir: ./x86_64
                  external_repository: atolycs/ardent-repo
                  publish_branch: main
                  cname: ${{ secrets.ACTIONS_CNAME }}
                  exclude_assets: 'CNAME'

    trigger_issue:
           runs-on: ubuntu-22.04
           needs: update_repo
           name: Trigger Issue Create
           steps:
            - name: Trigger Issue Create
              run: |
                gh issue create \
                   --title "[$(date +%Y%m%d-%H%m%S)] ArdentLinux Builded." \
                   --body "Check to [here](https://github.com/atolycs/ardent-repo.git)\n and Run\`sudo pacman -Sy\`\n If No problem then add Label\`lgtm\`"


#            - name: Upload Artifacts
#              uses: actions/upload-artifact@v3
#              with:
#                name: artifact_db
#                path: "*.pkg.tar.zst"
#            - name: Upload Artifacts
#              uses: actions/upload-artifact@v3
#              with:
#                name: artifact_db
#                path: "*.pkg.tar.zst.sig"
#            - name: Upload Artifacts
#              uses: actions/upload-artifact@v3
#              with:
#                name: artifact_db
#                path: "ardent-staging.*.tar.xz"
#            - name: Upload Artifacts
#              uses: actions/upload-artifact@v3
#              with:
#                name: artifact_db
#                path: "ardent-stable.*.tar.xz"
#    upload_stgrepo:
#        runs-on: ubuntu-22.04
#        name: Upload Staging Repository
#        needs: update_repo
#        steps:
#            - name: Checkout Staging Repo
#              uses: actions/checkout@v3
#              with:
#                repository: atolycs/ardent-repo
#                token: ${{ secrets.GH_TOKEN }}
#                ref: main
#            - name: Download Artifacts
#              uses: actions/download-artifact@v3
#              with:
#                name: artifact_db
#                path: ./artifacts_db
#            - name: Rsync Repo Data
#              run: |
#                ls -lsa
#                ls -lsa ./artifacts_db 
#                rsync -auvz ./artifacts_db/* ./x86_64
#                rm -rf ./artifacts_db
#            - name: Create Links
#              run: |
#                ln -sf ./ardent-staging.db.tar.xz ./x86_64/ardent-staging.db
#                ln -sf ./ardent-staging.files.tar.xz ./x86_64/ardent-staging.files
#                ln -sf ./ardent-stable.db.tar.xz ./x86_64/ardent-stable.db
#                ln -sf ./ardent-stable.files.tar.xz ./x86_64/ardent-stable.files
#            - name: Git config
#              env:
#                GIT_ACTION_MAIL: ${{ secrets.GIT_ACTION_EMAIL }}
#              run: |
#                git config --local user.name "Atolycs by Github Actions"
#                git config --local user.email ${GIT_ACTION_MAIL}
#            - name: Push
#              run: |
#                git add -A
#                git commit -m "[Action] Update Repository"
#                git pull
#                git push 
