name: Update submodules
run-name: Update ${{ github.ref_name }} submodules
on:
#    schedule:
#        - cron: '0 * * * *'
    workflow_dispatch:

jobs:
    update_submodules:
        name: Update submodules
        runs-on: ubuntu-latest
        env:
          TZ: "Asia/Tokyo"
        steps:
          - uses: actions/checkout@v2
            with:
              submodules: recursive

